nohup llamafactory-cli train \
    --stage sft \
    --do_train \
    --model_name_or_path /volume/pt-train/users/wzhang/sdx-workspace/models/LLM-Research/Meta-Llama-3.1-8B-Instruct \
    --template llama3 \
    --dataset mmt_train_think \
    --dataset_dir ./data \
    --finetuning_type full \
    --deepspeed examples/deepspeed/ds_z3_config.json \
    --output_dir /volume/pt-train/users/wzhang/sdx-workspace/models/sft/LLM-Research/Meta-Llama-3.1-8B-Instruct/epoch_5_lr_1e5_full_sft_think \
    --overwrite_cache \
    --overwrite_output_dir \
    --cutoff_len 12000 \
    --preprocessing_num_workers 16 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 50 \
    --warmup_ratio 0.1 \
    --save_steps 100 \
    --eval_steps 50 \
    --eval_strategy steps \
    --load_best_model_at_end \
    --learning_rate 1.0e-5 \
    --num_train_epochs 5.0 \
    --max_samples 50000 \
    --val_size 0.1 \
    --plot_loss \
    --bf16 > /volume/pt-train/users/wzhang/sdx-workspace/models/sft/LLM-Research/Meta-Llama-3.1-8B-Instruct/epoch_5_lr_1e5_full_sft_think.log 2>&1 &